name: my_music_player
description: My Music player project.
publish_to: 'none'
version: 2.0.0+2

environment:
  sdk: '>=3.1.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  get:
  just_audio:
  just_audio_background:
  path_provider:
  shared_preferences:
  get_storage:
  google_mobile_ads:
  social_share:
  url_launcher:
  flutter_spinkit:
  permission_handler:
  flutter_media_metadata:
  on_audio_query:


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "app_icon.jpeg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "app_icon.jpeg"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "app_icon.jpeg"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "app_icon.jpeg"

flutter:

  uses-material-design: true
  assets:
    - app_icon.jpeg